spring:
  profiles:
      include: oauth
  session:
    store-type: jdbc

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver