spring:
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver